AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EbsVolume:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone:
        Fn::Select: 
          - 0
          - Fn::GetAZs: ""
      Size: 25
      VolumeType: gp2
      Tags:
        - Key: Service
          Value:
            Ref: ServiceName
        - Key: Environment
          Value:
            Ref: EnvironmentName
Parameters:
  ServiceName:
    Type: String
    Default: jenkins
    Description: "The service name"
  EnvironmentName:
    Type: String
    Default: DevOps
    Description: "The environment name"