AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Ec2Sg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp:
          Ref: AdminLocationIp
      GroupName:
        Fn::Join:
        - ""
        - - Ref: ServiceName
          - "-sg"
      GroupDescription:
        Fn::Join:
        - ""
        - - "Security group for "
          - Ref: ServiceName
          - " instances"
      Tags:
        - Key: Service
          Value:
            Ref: ServiceName
        - Key: Environment
          Value:
            Ref: EnvironmentName
  EbsVolume:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone:
        Fn::Select: 
          - 0
          - Fn::GetAZs: ""
      Size: 25
      VolumeType: gp2
      Tags:
        - Key: Service
          Value:
            Ref: ServiceName
        - Key: Environment
          Value:
            Ref: EnvironmentName
  Ec2Intance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId:
        Ref: ImageId
      KeyName:
        Ref: KeyPairName
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds:
        - Ref: Ec2Sg
      SubnetId:
        Ref: Ec2InstanceSubnetId
      Monitoring: true
      Volumes:
        - Device: "/dev/sdk"
          VolumeId:
            Ref: EbsVolume
      Tags:
        - Key: Service
          Value:
            Ref: ServiceName
        - Key: Environment
          Value:
            Ref: EnvironmentName
        - Key: Name
          Value:
            Ref: ServiceName
Parameters:
  VpcId:
    Type: String
    Description: "VPC ID"
    Default: ''
  AdminLocationIp:
    Type: String
    Description: "IP address of the ops team location"
    Default: 1.2.3.4/32
  ServiceName:
    Type: String
    Default: jenkins
    Description: "The service name"
  EnvironmentName:
    Type: String
    Default: DevOps
    Description: "The environment name"
  KeyPairName:
    Type: String
    Default: ''
    Description: "The key pair name"
  ImageId:
    Type: String
    Default: ami-e21cc38c
    Description: "Image ID"
  InstanceType:
    Type: String
    Default: t2.micro
    Description: "The instance type"
  Ec2InstanceSubnetId:
    Type: String
    Default: ''
    Description: "Subnet ID where to launch the EC2 instance"